name: QQQ
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appdirs=1.4.4=pyhd8ed1ab_1
  - autograd=1.8.0=pyhd8ed1ab_0
  - brotli-python=1.2.0=py311h66f275b_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-nvml-dev=12.9.79=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-version=12.9=h4f385c5_3
  - custatevec=1.11.0=h58dd1b1_0
  - expat=2.7.3=h3385a95_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libcblas=3.11.0=2_h0358290_openblas
  - libcublas=12.9.1.4=h676940d_1
  - libcusparse=12.5.10.65=hecca717_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgomp=15.2.0=h4751f2c_7
  - liblapack=3.11.0=2_h47877c9_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.9.86=hecca717_2
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pennylane=0.37.0=py311h38be061_0
  - pennylane-core=0.37.0=py311h38be061_0
  - pennylane-lightning-core=0.37.0=hd45d622_0
  - pennylane-lightning-gpu=0.37.0=py311h71825b7_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h6fa692b_0
  - python-gil=3.11.14=hd8ed1ab_2
  - python_abi=3.11=2_cp311
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rustworkx=0.17.1=py310h1570de5_3
  - scipy=1.16.3=py311h1e13796_1
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - toml=0.10.2=pyhd8ed1ab_2
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - autoray==0.6.12
      - axial-positional-embedding==0.3.12
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - cffi==2.0.0
      - colt5-attention==0.11.1
      - commonmark==0.9.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - custatevec-cu12==1.11.0
      - cycler==0.12.1
      - defusedxml==0.7.1
      - dill==0.3.4
      - docutils==0.21.2
      - einops==0.8.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.61.0
      - fsspec==2025.9.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - hyper-connections==0.2.1
      - ibm-cloud-sdk-core==3.24.2
      - ibm-platform-services==0.71.0
      - imagesize==1.4.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - local-attention==1.11.2
      - loguru==0.7.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgpack-numpy==0.4.8
      - multimethod==2.0.2
      - multiprocess==0.70.12.2
      - namex==0.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nbsphinx==0.9.8
      - networkx==3.5
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pathos==0.2.8
      - patool==4.0.2
      - pillow==11.3.0
      - platformdirs==4.5.0
      - ply==3.11
      - pox==0.3.6
      - ppft==1.7.7
      - product-key-memory==0.3.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pyparsing==3.2.5
      - pyscf==2.11.0
      - pyspnego==0.12.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qiskit==0.46.3
      - qiskit-aer==0.12.2
      - qiskit-terra==0.46.3
      - recommonmark==0.7.1
      - referencing==0.37.0
      - reformer-pytorch==1.4.4
      - requests-ntlm==1.3.0
      - rich==14.2.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.29.0
      - scikit-base==0.13.0
      - scikit-learn==1.7.2
      - six==1.17.0
      - sktime==0.40.1
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==8.2.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stevedore==5.6.0
      - symengine==0.14.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorpack==0.11
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch==2.9.1+cu126
      - torchdiffeq==0.2.5
      - torchpack==0.3.1
      - torchquantum==0.1.8
      - torchvision==0.24.1+cu126
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.5.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - webencodings==0.5.1
      - werkzeug==3.1.4
      - wrapt==2.0.1
prefix: /home/ubuntu/miniconda/envs/QQQ
